Convert to dx9
rigidchips-lib/rigidchips pull request #121
Opened 2018-01-11 14:03 UTC by taka-tuos

重ね重ねプルリク
動作確認済み

2018-01-13 12:22 UTC, lempiji requested changes
気になった差分ちょっとコメントつけてみました。
git cloneしたあと、git merge origin/convert-to-dx9 して動作確認するとヘルプのロゴの方は確認できると思います。

2018-01-13 12:22 UTC, lempiji commented on Rigid8.vcxproj
> +      <AdditionalDependencies>dsound.lib;dinput8.lib;dxerr9.lib;d3dx9dt.lib;d3d9.lib;imm32.lib;d3dxof.lib;dxguid.lib;winmm.lib;odbc32.lib;odbccp32.lib</AdditionalDependencies>
;%(AdditionalDependencies)が消えてるようなので、たぶん残しておいてもらえると良い感じです

2018-01-13 12:22 UTC, lempiji commented on src/Rigidmain.cpp
> +		pos.x = w / 2.0f - 128.0f;
Help - Aboutで出てくるロゴが少し右に寄ってしまうようです。

2018-01-13 13:05 UTC, taka-tuos commented
指定された点修正しました
コンフリクト解消でやらかしてましたね

2018-01-13 16:36 UTC, ray45422 commented
リサイズすると動かなくなります
*マージ後対応でOK

2018-01-14 01:50 UTC, lempiji approved these changes

2018-01-14 14:02 UTC, merged